config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'
  resources :users
  resource :session, only: [:destroy,:new, :create ]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:destroy, :create, :update, :show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id
  )

  belongs_to(
    :post,
    class_name: 'Post',
    foreign_key: :post_id
  )

  has_many(
    :child_comments,
    class_name: 'Comment',
    foreign_key: :parent_comment_id
  )
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, :subs, presence: true

  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )


  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id
  )

  has_many(
    :post_subs, dependent: :destroy, inverse_of: :post,
    class_name: 'PostSub',
    foreign_key: :post_id
  )

  has_many(
    :comments, dependent: :destroy,
    class_name: 'Comment',
    foreign_key: :post_id
  )

  def top_comments
    self.comments.where(parent_comment_id: nil)
  end


end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :sub_id, :post, presence: true

  belongs_to(
    :sub,
    class_name: 'Sub',
    foreign_key: :sub_id
  )

  belongs_to(
    :post,
    class_name: 'Post',
    foreign_key: :post_id
  )
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to(
  :moderator,
  class_name: 'User',
  foreign_key: :user_id
  )

  has_many(
  :posts,
  through: :post_subs,
  source: :post
  )

  has_many(
  :post_subs, dependent: :destroy,
  class_name: 'PostSub',
  foreign_key: :sub_id
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: {messages: "password cannot be blank"}
  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= User.generate_sessions_token
  end

  def self.find_by_credential(email, password)
    user = User.find_by_email(email)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_sessions_token
    @session = SecureRandom.urlsafe_base64
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    new_token = User.generate_sessions_token
    self.session_token = new_token
    self.save
  end

  def is_password?(password)
    return true if BCrypt::Password.new(self.password_digest).is_password?(password)
    false
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :login!, :logout!, :current_user, :consequences_of_not_logged_in

  def login!(user)
    user.reset_session_token!
    current_user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    @current_user = nil
    reset_session
  end

  def consequences_of_not_logged_in
    unless logged_in?
      redirect_to new_session_url
    end
  end

  def logged_in?
    return false if current_user.nil?
    true
  end

  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :consequences_of_not_logged_in

  def new
    @comment = Comment.new
    @post_id = params[:post_id]
    @parent_id = params[:parent_id]
    render :new
  end

  def create
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id

    if comment.save
        redirect_to post_url(comment.post)
    else
      comment.errors.full_messages
    end
  end

  def show
    @comment = Comment.find_by_id(params[:id])
    render :show
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorized?, only: [:edit, :update]
  before_action :consequences_of_not_logged_in
  def new
    @post = Post.new
    render :new
  end

  def create
    post = Post.new(post_params)
    post.author_id = current_user.id
    if post.save!
      redirect_to post_url(post)
    else
      post.errors.full_messages
    end
  end

  def update
    post = Post.find_by_id(params[:id])
    post.update!(post_params)
    post.save
    redirect_to post_url(post)
  end

  def show
    @post = Post.find_by_id(params[:id])
    render :show
  end

  def edit
    @post = Post.find_by_id(params[:id])
    render :edit
  end

  private
  def authorized?
    if Post.find_by_id(params[:id]).author_id != current_user.id
      flash[:notice] = "you are not authorized to perform this action"
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :url, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credential(
          params[:session][:email],
          params[:session][:password]
    )
    if user
      login!(user)
      redirect_to root_url
    else
      render :new
      flash[:notice] = "email/password combination not found"
    end
  end

  def destroy
    logout!
    redirect_to root_url
  end


  private

  def user_params
    params.require(:user).permit(:email, :password_digest)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :authorized?, only: [:edit, :update]
    before_action :consequences_of_not_logged_in
    def authorized?
      unless Sub.find_by_id(params[:id]).user_id == current_user.id
        flash[:errors] = "only moderators are only to modify subs"
      end
    end

    def new
      @sub = Sub.new
      render :new
    end

    def edit
      @sub = Sub.find_by_id(params[:id])
      render :edit
    end

    def show
      @sub = Sub.find_by_id(params[:id])
    end

    def create
      new_subbie = Sub.new(sub_params)
      new_subbie.user_id = @current_user.id
      if new_subbie.save
        redirect_to sub_url(new_subbie)
      else
        new_subbie.errors.full_messages
      end
    end

    def update
      subbie = Sub.find_by_id(params[:id])
      subbie.update!(sub_params)
      redirect_to sub_url(subbie)
    end

    private
    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new 
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to root_url
    else
      redirect_to new_user_url
      flash[:notice] = user.errors.full_messages
    end
  end


  def user_params
    params.require(:user).permit(:email, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def auth_token
   html =
    "<input type= 'hidden'
     name= 'authenticity_token'
    value= #{form_authenticity_token}>"
   html.html_safe
 end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<!DOCTYPE html>
<html>
  <% action_url = comment.persisted? ? comment_url(comment) : comments_url%>
  <% input_value = comment.persisted? ? "PATCH" : "POST" %>
  <% submit_value = comment.persisted? ? "Update" : "Submit" %>
  <form action= "<%= action_url%>" method= "POST" >
    <input type="hidden" name="_method" value= <%= input_value %>>
    <%= auth_token %>

    <label for "comment-content">Content: </label>
    <textarea name="comment[content]"><%=comment.content%></textarea>
    <br>

    <input type="hidden" name= "comment[parent_comment_id]" value = "<%= @parent_id %>">
    <input type="hidden" name="comment[post_id]" value="<%= @post_id %>">

    <input type="submit"
      value= <%= submit_value %>>
  </form>
</html>

app/views/comments/_subcomment.html.erb
<% comment.child_comments.each do |cc| %>
<ul>
  <li>
    <%= cc.content %> <br>
    Author: <%= cc.author.email %>
    <%= link_to( "rely", new_post_comment_url(post_id: comment.post_id, parent_id: cc.id))%>

    <% unless cc.child_comments.empty? %>
      <%= render "comments/subcomment",  comment: cc %>
    <% end %>
  </li>
</ul>
<% end %>

app/views/comments/new.html.erb
<!DOCTYPE html>
<html>
  <%= render 'comments/form', comment: @comment %>
</html>

app/views/comments/show.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1>Top Comment:</h1>
    <%= @comment.content %> <br>
    Author: <%= @comment.author.email %>
    <br>
    <br>
    <h2>Sub-Comments:</h2>
    <%=link_to("Submit a SubComment!", new_post_comment_url(@comment.post, parent_id: @comment.id))%>
    <%= render "comments/subcomment", comment: @comment, post_id: @comment.post.id %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
  <%= %>
  <% if logged_in? %>
  Hello: <%= @current_user.email %>
  <br>
  <%= button_to "Log Out", session_url, method: :delete%>
  <% else %>
  <%= link_to "Log In", new_session_url %>
  <%= link_to "Create a New Account", new_user_url %>
  <% end %>
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  <%= yield %>
</head>
<body>


</body>
</html>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>
    URL:
    <input name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>
    Content:
    <textarea name="post[content]"><%= post.content %></textarea>
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |subbie| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= subbie.id %>"
        <%= "checked" if post.sub_ids.include?(subbie.id) %>>
      <%= subbie.title %>
    </label>
    <br>
  <% end %>

  <input type="Submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<h1> Edit <%= @post.title %>: </h1>
<%= render "posts/form", post: @post %>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<h1>Create a New Post</h1>
  <%= render "posts/form", post: @post %>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h2> <%= @post.title %>  </h2>
    <p>
      <%= @post.content %>
    </p>

    <%= link_to "Submit a Top Comment", new_post_comment_url(@post) %>
    <h3>Top Comments: </h3>
    <ul>
    <% @post.top_comments.each do |tc|%>
      <li>  <%= tc.content %> <br>
        author: <%= tc.author.email %> <br>
        <%= link_to "Details", comment_url(tc) %>
        <br>
        <h4>Sub-Comments:</h4>
        <ul> <% tc.child_comments.each do |cc| %>
          <li> <%= cc.content%> <br>
              author: <%= cc.author.email %>
              <%= render "comments/subcomment", comment: tc, post_id: tc.post_id, parent_id: cc.id %>
          </li>
          <% end %>
          <br>
        </ul>

      </li>
    <% end %>
    </ul>
  </body>
</html>

app/views/subs/_form.html.erb
<!DOCTYPE html>
<html>
<% action_url = subbie.persisted? ? sub_url(subbie) : subs_url %>
<% http_method = subbie.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
    <%= auth_token %>

    <label for "subs-title">Title: </label>
      <input id = "subs-title" type="text" name="sub[title]" value= <%= "#{subbie.title}" %>>
    <br>

    <label for="subs-description">Description: </label>
      <input id = "subs-description"
      type="text" name="sub[description]"
      value= <%= "#{subbie.description}"%>>
      <br>

    <input type="submit" value= <%= if subbie.persisted?
    "Update Sub"
    else
    "Submit This Sub"
    end%>>
  </form>
</html>

app/views/subs/edit.html.erb
<!DOCTYPE html>
<html>
  <%= render "subs/form", subbie: @sub %>
</html>

app/views/subs/index.html.erb
  <!DOCTYPE html>
<html>
  <body>
    <ul>
      <% Sub.all.order(:id).each do |sub| %>
        <li><%= link_to "#{sub.title}", sub_url(sub) %></li>
      <% end %>
    </ul>
    <%= link_to "Submit a new Sub!", new_sub_url %>
    <%= link_to "Create a Post", new_post_url %>
  </body>

</html>

app/views/subs/new.html.erb
<!DOCTYPE html>
<html>
  <%= render "subs/form", subbie: @sub %>
</html>

app/views/subs/show.html.erb
<!DOCTYPE html>
<html>
    <h1> <%= @sub.title %>
    <%= link_to "edit", edit_sub_url %>
  </h1>
    <p>
      <%= @sub.description %>
    </p>
    <h2>Related Posts:</h2>
    <ol> <% @sub.posts.each do |post| %>
      <li><%= post.title%><br>
          <%= post.content %><br>
          Submitted By: <%= post.author.email%> <br>
          Visit Post: <%= link_to "GO!", post_url(post) %>
          ||
            <% if @current_user ==  post.author  %>
              <%= link_to "Edit Post", edit_post_url(post), method: :patch%>
            <% end %>
          <% end %>
      </li>
    </ol>
</html>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html>
  <body>
    <form action="/users" method="post">
      <% if user.persisted? %>
       <input type="hidden" name="_method" value="patch">
      <% end %>
      <%= auth_token %>

      <label for="user-email">Email:
      <input type="text" name="user[email]" value = <%= "#{user.email}" if user.persisted? %>>
      </label>

      <label for="user-password">Password:
        <input type="text" name="user[password]">
      </label>

      <input type="submit"
      value= <%= if user.persisted?
                  "Update Account"
                else
                  "Create User"
                end%>>
    </form>
  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1>Update User</h1>
    <%= render "users/form", user: @user %>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <body>
     <% User.all.each do |n|%>
       <%= n.email %>
       <% end %>
       <br>
    <%= link_to "Create User", new_user_url %>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<body>
  <h1>Create a New User</h1>
  <%= render 'users/form', user: @user %>
  </body>
</html>